export const PokemonTypes = [
  { type: "poison", color: "#AD61AE" },
  { type: "grass", color: "#70B873" },
  { type: "fire", color: "#F44900" },
  { type: "flying", color: "#6892B0" },
  { type: "water", color: "#33A4F5" },
  { type: "bug", color: "#316520" },
  { type: "normal", color: "#8A8A8A" },
  { type: "dark", color: "#5C5365" },
  { type: "dragon", color: "#0A6CBF" },
  { type: "electric", color: "#F4D23B" },
  { type: "fairy", color: "#EC8FE6" },
  { type: "fighting", color: "#CE4069" },
  { type: "ghost", color: "#5269AC" },
  { type: "ground", color: "#D97745" },
  { type: "ice", color: "##74CEC0" },
  { type: "psychic", color: "#F67176" },
  { type: "rock", color: "#C7B78B" },
  { type: "steel", color: "#BBBBBB" },
];
