export const PokemonTypes = [
  { type: "poison", color: "#AD61AE" },
  { type: "grass", color: "#729F92" },
  { type: "fire", color: "#EAAB7D" },
  { type: "flying", color: "#6892B0" },
  { type: "water", color: "#71C3FF" },
  { type: "bug", color: "#76A866" },
  { type: "normal", color: "#BF9762" },
  { type: "dark", color: "#5C5365" },
  { type: "dragon", color: "#004170" },
  { type: "electric", color: "#FFA500" },
  { type: "fairy", color: "#EC8FE6" },
  { type: "fighting", color: "#CE4069" },
  { type: "ghost", color: "#5269AC" },
  { type: "ground", color: "#D97745" },
  { type: "ice", color: "##74CEC0" },
  { type: "psychic", color: "#F67176" },
  { type: "rock", color: "#C7B78B" },
  { type: "steel", color: "#BBBBBB" },
];
